use applevisor_sys::hv_error_t;
use applevisor_sys::hv_reg_t;
use applevisor_sys::hv_simd_fp_reg_t;
use applevisor_sys::hv_sys_reg_t;
use applevisor_sys::hv_vcpu_get_reg;

use crate::arch::aarch64::vcpu::reg::CoreRegister;
use crate::arch::aarch64::vcpu::reg::FpRegister;
use crate::arch::aarch64::vcpu::reg::SysRegister;
use crate::virtualization::hvp::hv_unsafe_call;
use crate::virtualization::vcpu::error::VcpuError;

pub enum HvpReg {
    CoreReg(hv_reg_t),
    SysReg(hv_sys_reg_t),
}

impl From<CoreRegister> for HvpReg {
    fn from(reg: CoreRegister) -> Self {
        match reg {
            CoreRegister::X0 => HvpReg::CoreReg(hv_reg_t::X0),
            CoreRegister::X1 => HvpReg::CoreReg(hv_reg_t::X1),
            CoreRegister::X2 => HvpReg::CoreReg(hv_reg_t::X2),
            CoreRegister::X3 => HvpReg::CoreReg(hv_reg_t::X3),
            CoreRegister::X4 => HvpReg::CoreReg(hv_reg_t::X4),
            CoreRegister::X5 => HvpReg::CoreReg(hv_reg_t::X5),
            CoreRegister::X6 => HvpReg::CoreReg(hv_reg_t::X6),
            CoreRegister::X7 => HvpReg::CoreReg(hv_reg_t::X7),
            CoreRegister::X8 => HvpReg::CoreReg(hv_reg_t::X8),
            CoreRegister::X9 => HvpReg::CoreReg(hv_reg_t::X9),
            CoreRegister::X10 => HvpReg::CoreReg(hv_reg_t::X10),
            CoreRegister::X11 => HvpReg::CoreReg(hv_reg_t::X11),
            CoreRegister::X12 => HvpReg::CoreReg(hv_reg_t::X12),
            CoreRegister::X13 => HvpReg::CoreReg(hv_reg_t::X13),
            CoreRegister::X14 => HvpReg::CoreReg(hv_reg_t::X14),
            CoreRegister::X15 => HvpReg::CoreReg(hv_reg_t::X15),
            CoreRegister::X16 => HvpReg::CoreReg(hv_reg_t::X16),
            CoreRegister::X17 => HvpReg::CoreReg(hv_reg_t::X17),
            CoreRegister::X18 => HvpReg::CoreReg(hv_reg_t::X18),
            CoreRegister::X19 => HvpReg::CoreReg(hv_reg_t::X19),
            CoreRegister::X20 => HvpReg::CoreReg(hv_reg_t::X20),
            CoreRegister::X21 => HvpReg::CoreReg(hv_reg_t::X21),
            CoreRegister::X22 => HvpReg::CoreReg(hv_reg_t::X22),
            CoreRegister::X23 => HvpReg::CoreReg(hv_reg_t::X23),
            CoreRegister::X24 => HvpReg::CoreReg(hv_reg_t::X24),
            CoreRegister::X25 => HvpReg::CoreReg(hv_reg_t::X25),
            CoreRegister::X26 => HvpReg::CoreReg(hv_reg_t::X26),
            CoreRegister::X27 => HvpReg::CoreReg(hv_reg_t::X27),
            CoreRegister::X28 => HvpReg::CoreReg(hv_reg_t::X28),
            CoreRegister::X29 => HvpReg::CoreReg(hv_reg_t::X29),
            CoreRegister::X30 => HvpReg::CoreReg(hv_reg_t::X30),
            CoreRegister::SP => HvpReg::SysReg(hv_sys_reg_t::SP_EL0),
            CoreRegister::PC => HvpReg::CoreReg(hv_reg_t::PC),
            CoreRegister::PState => HvpReg::CoreReg(hv_reg_t::CPSR),
            CoreRegister::Fpcr => HvpReg::CoreReg(hv_reg_t::FPCR),
            CoreRegister::Fpsr => HvpReg::CoreReg(hv_reg_t::FPSR),
        }
    }
}

impl From<FpRegister> for hv_simd_fp_reg_t {
    fn from(reg: FpRegister) -> Self {
        match reg {
            FpRegister::V0 => hv_simd_fp_reg_t::Q0,
            FpRegister::V1 => hv_simd_fp_reg_t::Q1,
            FpRegister::V2 => hv_simd_fp_reg_t::Q2,
            FpRegister::V3 => hv_simd_fp_reg_t::Q3,
            FpRegister::V4 => hv_simd_fp_reg_t::Q4,
            FpRegister::V5 => hv_simd_fp_reg_t::Q5,
            FpRegister::V6 => hv_simd_fp_reg_t::Q6,
            FpRegister::V7 => hv_simd_fp_reg_t::Q7,
            FpRegister::V8 => hv_simd_fp_reg_t::Q8,
            FpRegister::V9 => hv_simd_fp_reg_t::Q9,
            FpRegister::V10 => hv_simd_fp_reg_t::Q10,
            FpRegister::V11 => hv_simd_fp_reg_t::Q11,
            FpRegister::V12 => hv_simd_fp_reg_t::Q12,
            FpRegister::V13 => hv_simd_fp_reg_t::Q13,
            FpRegister::V14 => hv_simd_fp_reg_t::Q14,
            FpRegister::V15 => hv_simd_fp_reg_t::Q15,
            FpRegister::V16 => hv_simd_fp_reg_t::Q16,
            FpRegister::V17 => hv_simd_fp_reg_t::Q17,
            FpRegister::V18 => hv_simd_fp_reg_t::Q18,
            FpRegister::V19 => hv_simd_fp_reg_t::Q19,
            FpRegister::V20 => hv_simd_fp_reg_t::Q20,
            FpRegister::V21 => hv_simd_fp_reg_t::Q21,
            FpRegister::V22 => hv_simd_fp_reg_t::Q22,
            FpRegister::V23 => hv_simd_fp_reg_t::Q23,
            FpRegister::V24 => hv_simd_fp_reg_t::Q24,
            FpRegister::V25 => hv_simd_fp_reg_t::Q25,
            FpRegister::V26 => hv_simd_fp_reg_t::Q26,
            FpRegister::V27 => hv_simd_fp_reg_t::Q27,
            FpRegister::V28 => hv_simd_fp_reg_t::Q28,
            FpRegister::V29 => hv_simd_fp_reg_t::Q29,
            FpRegister::V30 => hv_simd_fp_reg_t::Q30,
            FpRegister::V31 => hv_simd_fp_reg_t::Q31,
        }
    }
}

impl From<SysRegister> for hv_sys_reg_t {
    fn from(reg: SysRegister) -> Self {
        match reg {
            SysRegister::Dbgbvr0El1 => hv_sys_reg_t::DBGBVR0_EL1,
            SysRegister::Dbgbcr0El1 => hv_sys_reg_t::DBGBCR0_EL1,
            SysRegister::Dbgwvr0El1 => hv_sys_reg_t::DBGWVR0_EL1,
            SysRegister::Dbgwcr0El1 => hv_sys_reg_t::DBGWCR0_EL1,
            SysRegister::Dbgbvr1El1 => hv_sys_reg_t::DBGBVR1_EL1,
            SysRegister::Dbgbcr1El1 => hv_sys_reg_t::DBGBCR1_EL1,
            SysRegister::Dbgwvr1El1 => hv_sys_reg_t::DBGWVR1_EL1,
            SysRegister::Dbgwcr1El1 => hv_sys_reg_t::DBGWCR1_EL1,
            SysRegister::MdccintEl1 => hv_sys_reg_t::MDCCINT_EL1,
            SysRegister::MdscrEl1 => hv_sys_reg_t::MDSCR_EL1,
            SysRegister::Dbgbvr2El1 => hv_sys_reg_t::DBGBVR2_EL1,
            SysRegister::Dbgbcr2El1 => hv_sys_reg_t::DBGBCR2_EL1,
            SysRegister::Dbgwvr2El1 => hv_sys_reg_t::DBGWVR2_EL1,
            SysRegister::Dbgwcr2El1 => hv_sys_reg_t::DBGWCR2_EL1,
            SysRegister::Dbgbvr3El1 => hv_sys_reg_t::DBGBVR3_EL1,
            SysRegister::Dbgbcr3El1 => hv_sys_reg_t::DBGBCR3_EL1,
            SysRegister::Dbgwvr3El1 => hv_sys_reg_t::DBGWVR3_EL1,
            SysRegister::Dbgwcr3El1 => hv_sys_reg_t::DBGWCR3_EL1,
            SysRegister::Dbgbvr4El1 => hv_sys_reg_t::DBGBVR4_EL1,
            SysRegister::Dbgbcr4El1 => hv_sys_reg_t::DBGBCR4_EL1,
            SysRegister::Dbgwvr4El1 => hv_sys_reg_t::DBGWVR4_EL1,
            SysRegister::Dbgwcr4El1 => hv_sys_reg_t::DBGWCR4_EL1,
            SysRegister::Dbgbvr5El1 => hv_sys_reg_t::DBGBVR5_EL1,
            SysRegister::Dbgbcr5El1 => hv_sys_reg_t::DBGBCR5_EL1,
            SysRegister::Dbgwvr5El1 => hv_sys_reg_t::DBGWVR5_EL1,
            SysRegister::Dbgwcr5El1 => hv_sys_reg_t::DBGWCR5_EL1,
            SysRegister::Dbgbvr6El1 => hv_sys_reg_t::DBGBVR6_EL1,
            SysRegister::Dbgbcr6El1 => hv_sys_reg_t::DBGBCR6_EL1,
            SysRegister::Dbgwvr6El1 => hv_sys_reg_t::DBGWVR6_EL1,
            SysRegister::Dbgwcr6El1 => hv_sys_reg_t::DBGWCR6_EL1,
            SysRegister::Dbgbvr7El1 => hv_sys_reg_t::DBGBVR7_EL1,
            SysRegister::Dbgbcr7El1 => hv_sys_reg_t::DBGBCR7_EL1,
            SysRegister::Dbgwvr7El1 => hv_sys_reg_t::DBGWVR7_EL1,
            SysRegister::Dbgwcr7El1 => hv_sys_reg_t::DBGWCR7_EL1,
            SysRegister::Dbgbvr8El1 => hv_sys_reg_t::DBGBVR8_EL1,
            SysRegister::Dbgbcr8El1 => hv_sys_reg_t::DBGBCR8_EL1,
            SysRegister::Dbgwvr8El1 => hv_sys_reg_t::DBGWVR8_EL1,
            SysRegister::Dbgwcr8El1 => hv_sys_reg_t::DBGWCR8_EL1,
            SysRegister::Dbgbvr9El1 => hv_sys_reg_t::DBGBVR9_EL1,
            SysRegister::Dbgbcr9El1 => hv_sys_reg_t::DBGBCR9_EL1,
            SysRegister::Dbgwvr9El1 => hv_sys_reg_t::DBGWVR9_EL1,
            SysRegister::Dbgwcr9El1 => hv_sys_reg_t::DBGWCR9_EL1,
            SysRegister::Dbgbvr10El1 => hv_sys_reg_t::DBGBVR10_EL1,
            SysRegister::Dbgbcr10El1 => hv_sys_reg_t::DBGBCR10_EL1,
            SysRegister::Dbgwvr10El1 => hv_sys_reg_t::DBGWVR10_EL1,
            SysRegister::Dbgwcr10El1 => hv_sys_reg_t::DBGWCR10_EL1,
            SysRegister::Dbgbvr11El1 => hv_sys_reg_t::DBGBVR11_EL1,
            SysRegister::Dbgbcr11El1 => hv_sys_reg_t::DBGBCR11_EL1,
            SysRegister::Dbgwvr11El1 => hv_sys_reg_t::DBGWVR11_EL1,
            SysRegister::Dbgwcr11El1 => hv_sys_reg_t::DBGWCR11_EL1,
            SysRegister::Dbgbvr12El1 => hv_sys_reg_t::DBGBVR12_EL1,
            SysRegister::Dbgbcr12El1 => hv_sys_reg_t::DBGBCR12_EL1,
            SysRegister::Dbgwvr12El1 => hv_sys_reg_t::DBGWVR12_EL1,
            SysRegister::Dbgwcr12El1 => hv_sys_reg_t::DBGWCR12_EL1,
            SysRegister::Dbgbvr13El1 => hv_sys_reg_t::DBGBVR13_EL1,
            SysRegister::Dbgbcr13El1 => hv_sys_reg_t::DBGBCR13_EL1,
            SysRegister::Dbgwvr13El1 => hv_sys_reg_t::DBGWVR13_EL1,
            SysRegister::Dbgwcr13El1 => hv_sys_reg_t::DBGWCR13_EL1,
            SysRegister::Dbgbvr14El1 => hv_sys_reg_t::DBGBVR14_EL1,
            SysRegister::Dbgbcr14El1 => hv_sys_reg_t::DBGBCR14_EL1,
            SysRegister::Dbgwvr14El1 => hv_sys_reg_t::DBGWVR14_EL1,
            SysRegister::Dbgwcr14El1 => hv_sys_reg_t::DBGWCR14_EL1,
            SysRegister::Dbgbvr15El1 => hv_sys_reg_t::DBGBVR15_EL1,
            SysRegister::Dbgbcr15El1 => hv_sys_reg_t::DBGBCR15_EL1,
            SysRegister::Dbgwvr15El1 => hv_sys_reg_t::DBGWVR15_EL1,
            SysRegister::Dbgwcr15El1 => hv_sys_reg_t::DBGWCR15_EL1,
            SysRegister::MidrEl1 => hv_sys_reg_t::MIDR_EL1,
            SysRegister::MpidrEl1 => hv_sys_reg_t::MPIDR_EL1,
            SysRegister::IdAa64pfr0El1 => hv_sys_reg_t::ID_AA64PFR0_EL1,
            SysRegister::IdAa64pfr1El1 => hv_sys_reg_t::ID_AA64PFR1_EL1,
            SysRegister::IdAa64zfr0El1 => hv_sys_reg_t::ID_AA64ZFR0_EL1,
            SysRegister::IdAa64smfr0El1 => hv_sys_reg_t::ID_AA64SMFR0_EL1,
            SysRegister::IdAa64dfr0El1 => hv_sys_reg_t::ID_AA64DFR0_EL1,
            SysRegister::IdAa64dfr1El1 => hv_sys_reg_t::ID_AA64DFR1_EL1,
            SysRegister::IdAa64isar0El1 => hv_sys_reg_t::ID_AA64ISAR0_EL1,
            SysRegister::IdAa64isar1El1 => hv_sys_reg_t::ID_AA64ISAR1_EL1,
            SysRegister::IdAa64mmfr0El1 => hv_sys_reg_t::ID_AA64MMFR0_EL1,
            SysRegister::IdAa64mmfr1El1 => hv_sys_reg_t::ID_AA64MMFR1_EL1,
            SysRegister::IdAa64mmfr2El1 => hv_sys_reg_t::ID_AA64MMFR2_EL1,
            SysRegister::SctlrEl1 => hv_sys_reg_t::SCTLR_EL1,
            SysRegister::CpacrEl1 => hv_sys_reg_t::CPACR_EL1,
            SysRegister::ActlrEl1 => hv_sys_reg_t::ACTLR_EL1,
            SysRegister::SmpriEl1 => hv_sys_reg_t::SMPRI_EL1,
            SysRegister::SmcrEl1 => hv_sys_reg_t::SMCR_EL1,
            SysRegister::Ttbr0El1 => hv_sys_reg_t::TTBR0_EL1,
            SysRegister::Ttbr1El1 => hv_sys_reg_t::TTBR1_EL1,
            SysRegister::TcrEl1 => hv_sys_reg_t::TCR_EL1,
            SysRegister::ApiakeyloEl1 => hv_sys_reg_t::APIAKEYLO_EL1,
            SysRegister::ApiakeyhiEl1 => hv_sys_reg_t::APIAKEYHI_EL1,
            SysRegister::ApibkeyloEl1 => hv_sys_reg_t::APIBKEYLO_EL1,
            SysRegister::ApibkeyhiEl1 => hv_sys_reg_t::APIBKEYHI_EL1,
            SysRegister::ApdakeyloEl1 => hv_sys_reg_t::APDAKEYLO_EL1,
            SysRegister::ApdakeyhiEl1 => hv_sys_reg_t::APDAKEYHI_EL1,
            SysRegister::ApdbkeyloEl1 => hv_sys_reg_t::APDBKEYLO_EL1,
            SysRegister::ApdbkeyhiEl1 => hv_sys_reg_t::APDBKEYHI_EL1,
            SysRegister::ApgakeyloEl1 => hv_sys_reg_t::APGAKEYLO_EL1,
            SysRegister::ApgakeyhiEl1 => hv_sys_reg_t::APGAKEYHI_EL1,
            SysRegister::SpsrEl1 => hv_sys_reg_t::SPSR_EL1,
            SysRegister::ElrEl1 => hv_sys_reg_t::ELR_EL1,
            SysRegister::SpEl0 => hv_sys_reg_t::SP_EL0,
            SysRegister::Afsr0El1 => hv_sys_reg_t::AFSR0_EL1,
            SysRegister::Afsr1El1 => hv_sys_reg_t::AFSR1_EL1,
            SysRegister::EsrEl1 => hv_sys_reg_t::ESR_EL1,
            SysRegister::FarEl1 => hv_sys_reg_t::FAR_EL1,
            SysRegister::ParEl1 => hv_sys_reg_t::PAR_EL1,
            SysRegister::MairEl1 => hv_sys_reg_t::MAIR_EL1,
            SysRegister::AmairEl1 => hv_sys_reg_t::AMAIR_EL1,
            SysRegister::VbarEl1 => hv_sys_reg_t::VBAR_EL1,
            SysRegister::ContextidrEl1 => hv_sys_reg_t::CONTEXTIDR_EL1,
            SysRegister::TpidrEl1 => hv_sys_reg_t::TPIDR_EL1,
            SysRegister::ScxtnumEl1 => hv_sys_reg_t::SCXTNUM_EL1,
            SysRegister::CntkctlEl1 => hv_sys_reg_t::CNTKCTL_EL1,
            SysRegister::CsselrEl1 => hv_sys_reg_t::CSSELR_EL1,
            SysRegister::TpidrEl0 => hv_sys_reg_t::TPIDR_EL0,
            SysRegister::TpidrroEl0 => hv_sys_reg_t::TPIDRRO_EL0,
            SysRegister::Tpidr2El0 => hv_sys_reg_t::TPIDR2_EL0,
            SysRegister::ScxtnumEl0 => hv_sys_reg_t::SCXTNUM_EL0,
            SysRegister::CntvCtlEl0 => hv_sys_reg_t::CNTV_CTL_EL0,
            SysRegister::CntvCvalEl0 => hv_sys_reg_t::CNTV_CVAL_EL0,
            SysRegister::SpEl1 => hv_sys_reg_t::SP_EL1,
            SysRegister::CntpCtlEl0 => hv_sys_reg_t::CNTP_CTL_EL0,
            SysRegister::CntpCvalEl0 => hv_sys_reg_t::CNTP_CVAL_EL0,
            SysRegister::CntpTvalEl0 => hv_sys_reg_t::CNTP_TVAL_EL0,
            SysRegister::CnthctlEl2 => hv_sys_reg_t::CNTHCTL_EL2,
            SysRegister::CnthpCtlEl2 => hv_sys_reg_t::CNTHP_CTL_EL2,
            SysRegister::CnthpCvalEl2 => hv_sys_reg_t::CNTHP_CVAL_EL2,
            SysRegister::CnthpTvalEl2 => hv_sys_reg_t::CNTHP_TVAL_EL2,
            SysRegister::CntvoffEl2 => hv_sys_reg_t::CNTVOFF_EL2,
            SysRegister::CptrEl2 => hv_sys_reg_t::CPTR_EL2,
            SysRegister::ElrEl2 => hv_sys_reg_t::ELR_EL2,
            SysRegister::EsrEl2 => hv_sys_reg_t::ESR_EL2,
            SysRegister::FarEl2 => hv_sys_reg_t::FAR_EL2,
            SysRegister::HcrEl2 => hv_sys_reg_t::HCR_EL2,
            SysRegister::HpfarEl2 => hv_sys_reg_t::HPFAR_EL2,
            SysRegister::MairEl2 => hv_sys_reg_t::MAIR_EL2,
            SysRegister::MdcrEl2 => hv_sys_reg_t::MDCR_EL2,
            SysRegister::SctlrEl2 => hv_sys_reg_t::SCTLR_EL2,
            SysRegister::SpsrEl2 => hv_sys_reg_t::SPSR_EL2,
            SysRegister::SpEl2 => hv_sys_reg_t::SP_EL2,
            SysRegister::TcrEl2 => hv_sys_reg_t::TCR_EL2,
            SysRegister::TpidrEl2 => hv_sys_reg_t::TPIDR_EL2,
            SysRegister::Ttbr0El2 => hv_sys_reg_t::TTBR0_EL2,
            SysRegister::Ttbr1El2 => hv_sys_reg_t::TTBR1_EL2,
            SysRegister::VbarEl2 => hv_sys_reg_t::VBAR_EL2,
            SysRegister::VmpidrEl2 => hv_sys_reg_t::VMPIDR_EL2,
            SysRegister::VpidrEl2 => hv_sys_reg_t::VPIDR_EL2,
            SysRegister::VtcrEl2 => hv_sys_reg_t::VTCR_EL2,
            SysRegister::VttbrEl2 => hv_sys_reg_t::VTTBR_EL2,
            SysRegister::OslarEl1 => todo!(),
            SysRegister::OslsrEl1 => todo!(),
            SysRegister::OsdlrEl1 => todo!(),
        }
    }
}

pub unsafe fn get_reg(vcpu: u64, rt: u64) -> Result<u64, VcpuError> {
    let mut data = 0;

    if rt != 31 {
        let reg = match rt {
            0 => hv_reg_t::X0,
            1 => hv_reg_t::X1,
            2 => hv_reg_t::X2,
            3 => hv_reg_t::X3,
            4 => hv_reg_t::X4,
            5 => hv_reg_t::X5,
            6 => hv_reg_t::X6,
            19 => hv_reg_t::X19,
            21 => hv_reg_t::X21,
            22 => hv_reg_t::X22,
            _ => unimplemented!("{rt}"),
        };
        hv_unsafe_call!(hv_vcpu_get_reg(vcpu, reg, &mut data))?;
    };

    Ok(data)
}
