use zerocopy::{Immutable, IntoBytes};

use crate::acpi::r#type::common_header::CommonHeader;
use crate::acpi::r#type::generic_address_structure_format::GenericAddressStructureFormat;

#[derive(Default, Immutable, IntoBytes)]
#[repr(C, packed)]
pub struct Fadt {
    header: CommonHeader,
    firmware_ctrl: u32,
    dsdt: u32,
    reserved_0: u8,
    preferred_pm_profile: u8,
    sci_int: u16,
    smi_cmd: u32,
    acpi_enable: u8,
    acpi_disable: u8,
    s4bios_req: u8,
    pstate_cnt: u8,
    pm1a_evt_blk: u32,
    pm1b_evt_blk: u32,
    pm1a_cnt_blk: u32,
    pm1b_cnt_blk: u32,
    pm2_cnt_blk: u32,
    pm_tmr_blk: u32,
    gpe0_blk: u32,
    gpe1_blk: u32,
    pm1_evt_len: u8,
    pm1_cnt_len: u8,
    pm2_cnt_len: u8,
    pm_tmr_len: u8,
    gpe0_blk_len: u8,
    gpe1_blk_len: u8,
    gpe1_base: u8,
    cst_cnt: u8,
    p_lvl2_lat: u16,
    p_lvl3_lat: u16,
    flush_size: u16,
    flush_stride: u16,
    duty_offset: u8,
    duty_width: u8,
    day_alrm: u8,
    mon_alrm: u8,
    century: u8,
    iapc_boot_arch: u16,
    reserved_1: u8,
    flags: u32,
    reset_reg: GenericAddressStructureFormat,
    reset_value: u8,
    arm_boot_arch: u16,
    fadt_minor_version: u8,
    x_firmware_ctrl: u64,
    x_dsdt: u64,
    x_pm1a_evt_blk: GenericAddressStructureFormat,
    x_pm1b_evt_blk: GenericAddressStructureFormat,
    x_pm1a_cnt_blk: GenericAddressStructureFormat,
    x_pm1b_cnt_blk: GenericAddressStructureFormat,
    x_pm2_cnt_blk: GenericAddressStructureFormat,
    x_pm_tmr_blk: GenericAddressStructureFormat,
    x_gpe0_blk: GenericAddressStructureFormat,
    x_gpe1_blk: GenericAddressStructureFormat,
    sleep_control_reg: GenericAddressStructureFormat,
    sleep_status_reg: GenericAddressStructureFormat,
    hypervisor_vendor_id: [u8; 8],
}

impl Fadt {}
