const PSCI_VERSION_MAJOR_SHIFT: u32 = 16;
const PSCI_VERSION_MINOR_MASK: u32 = (1 << PSCI_VERSION_MAJOR_SHIFT) - 1;
const PSCI_VERSION_MAJOR_MASK: u32 = !PSCI_VERSION_MINOR_MASK;

pub const fn psci_version(maj: u32, min: u32) -> u32 {
    ((maj << PSCI_VERSION_MAJOR_SHIFT) & PSCI_VERSION_MAJOR_MASK) | (min & PSCI_VERSION_MINOR_MASK)
}
