name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUST_BACKTRACE: 1
  RUST_STABLE: 1.95.0
  RUST_NIGHTLY: nightly-2026-05-30

defaults:
  run:
    shell: bash

jobs:
  build_x86_64_kvm:
    name: Build(X86_64/Kvm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
      - uses: Swatinem/rust-cache@v2
      - name: Build(X86_64/Kvm)
        run: cargo build --verbose

  build_arm64_kvm:
    name: Build(Arm64/Kvm)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
      - uses: Swatinem/rust-cache@v2
      - name: Build(Arm64/Kvm)
        run: cargo build --verbose

  build_arm64_hvp:
    name: Build(Arm64/hvp)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
      - uses: Swatinem/rust-cache@v2
      - name: build(Arm64/hvp)
        run: cargo build --verbose

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          components: rustfmt
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --check

  clippy-x86_64_kvm:
    name: Clippy(x86_64/Kvm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: clippy
        run: cargo clippy --all-targets

  clippy-aarch64_kvm:
    name: Clippy(Arm64/Kvm)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: clippy
        run: cargo clippy --all-targets

  clippy-aarch64_hvp:
    name: Clippy(Arm64/hvp)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: clippy
        run: cargo clippy --all-targets

  udeps-x86_64_kvm:
    name: Udeps(x86_64/Kvm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps
      - name: udeps
        run: cargo udeps --all-targets

  udeps-aarch64_kvm:
    name: Udeps(Arm64/Kvm)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps
      - name: udeps
        run: cargo udeps --all-targets

  udeps-aarch64_hvp:
    name: Udeps(Arm64/hvp)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps
      - name: udeps
        run: cargo udeps --all-targets

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: udeps
        run: cargo test
